# Generated by Django 4.2.3 on 2023-07-17 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField(blank=True, null=True)),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalDavEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('etag', models.CharField(max_length=30)),
                ('dtstart', models.DateTimeField()),
                ('dtend', models.DateTimeField()),
                ('summary', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_caldav_event.calendarinfos')),
            ],
        ),
    ]
