# Generated by Django 4.2.3 on 2023-07-17 22:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_caldav_event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('status', models.SmallIntegerField(choices=[(1, 'Requested'), (2, 'Accepted'), (3, 'Denied'), (4, 'Changed')], default=1)),
                ('end_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('commentary', models.CharField(blank=True, max_length=300, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facusers.project')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('unit', models.SmallIntegerField(choices=[(2, 'm'), (3, 'm2'), (4, 'm3'), (5, 'g'), (6, 'p')], default=5)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('models', models.ManyToManyField(blank=True, to='faccore.machinemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimedResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('timedresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='faccore.timedresource')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('faccore.timedresource', models.Model),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('timedresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='faccore.timedresource')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('faccore.timedresource', models.Model),
        ),
        migrations.CreateModel(
            name='TrainingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0)),
                ('need_manager', models.BooleanField(default=True)),
                ('machine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faccore.machinemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('validated', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='faccore.reservation')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='faccore.supply')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('min_time_slot', models.DecimalField(decimal_places=3, default=0.5, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_time_slot', models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('need_manager', models.BooleanField(default=False)),
                ('needs', models.ManyToManyField(blank=True, to='faccore.machinemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faccore.reservationtype'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='user_levels',
            field=models.ManyToManyField(blank=True, related_name='training_levels', through='faccore.TrainingLevel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('resources', models.ManyToManyField(to='faccore.timedresource')),
            ],
        ),
        migrations.AddConstraint(
            model_name='traininglevel',
            constraint=models.UniqueConstraint(fields=('machine_model', 'user'), name='One training level per user/machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='faccore.machinemodel'),
        ),
        migrations.RemoveField(
            model_name='reservationtype',
            name='max_time_slot',
        ),
        migrations.RemoveField(
            model_name='reservationtype',
            name='min_time_slot',
        ),
        migrations.RemoveField(
            model_name='reservationtype',
            name='needs',
        ),
        migrations.AddField(
            model_name='event',
            name='closing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationtype',
            name='machine_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faccore.machinemodel'),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='TimedResource',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_caldav_event.calendarinfos')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='faccore.machinemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faccore.machine'),
        ),
        migrations.AddField(
            model_name='reservationtype',
            name='spe_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='faccore.manager'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faccore.manager'),
        ),
    ]
