# Generated by Django 4.2.3 on 2024-01-31 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_caldav_event', '0001_initial'),
        ('faccore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='calendar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='django_caldav_event.calendarinfos'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='unit',
            field=models.SmallIntegerField(choices=[(2, 'm'), (3, 'm2'), (4, 'm3'), (5, 'g'), (6, 'p'), (7, 'ml'), (8, 'h')], default=5),
        ),
    ]
