# Generated by Django 4.0.2 on 2022-03-20 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facusers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faccore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplyusage',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='faccore.reservation'),
        ),
        migrations.AddField(
            model_name='supplyusage',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='faccore.supply'),
        ),
        migrations.AddField(
            model_name='supply',
            name='models',
            field=models.ManyToManyField(blank=True, to='faccore.MachineModel'),
        ),
        migrations.AddField(
            model_name='reservationtype',
            name='needs',
            field=models.ManyToManyField(blank=True, to='faccore.MachineModel'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facusers.project'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faccore.reservationtype'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='machinemodel',
            name='user_levels',
            field=models.ManyToManyField(blank=True, related_name='training_levels', through='faccore.TrainingLevel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availability',
            name='resources',
            field=models.ManyToManyField(to='faccore.TimedResource'),
        ),
        migrations.AddConstraint(
            model_name='traininglevel',
            constraint=models.UniqueConstraint(fields=('machine_model', 'user'), name='One training level per user/machine'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faccore.manager'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='uses',
            field=models.ManyToManyField(blank=True, to='faccore.Machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='faccore.machinemodel'),
        ),
    ]
