# Generated by Django 5.2.5 on 2025-09-02 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faccore', '0002_alter_manager_calendar_alter_supply_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglevel',
            name='level',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
