# Generated by Django 5.2.5 on 2026-01-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faccore', '0003_alter_traininglevel_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='calendar',
        ),
        migrations.AddField(
            model_name='manager',
            name='business_hours',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
