# Generated by Django 5.2.5 on 2026-01-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faccore', '0004_remove_manager_calendar_manager_business_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='business_hours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
